//TODO input can affect only focused window
//TODO add container control like border/scroll/stackpanel/grid...
//TODO add common dialog like msgbox
//TODO Extend textbox: passwordbox, auto-complete, x mark for clear input, ...